// scripts/html-builder.js
// Remplace la fonction `run()` dans generate-digest.js

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, readdirSync } from 'fs';

function verdictClass(verdict) {
  if (verdict.includes('upgrade now')) return 'verdict-now';
  if (verdict.includes('watch'))       return 'verdict-watch';
  return 'verdict-skip';
}

function parseGeminiMarkdown(markdown) {
  const lines = markdown.split('\n');
  let html = '';
  let sectionCount = 0;
  let inSection = false;
  let inActions = false;
  let priorityText = '';
  let inPriority = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    // Priority section
    if (line.startsWith('## This week') || line.startsWith("## This Week")) {
      inPriority = true;
      inSection = false;
      inActions = false;
      continue;
    }

    if (inPriority && line && !line.startsWith('#')) {
      priorityText += line + ' ';
      continue;
    }

    if (inPriority && line.startsWith('#')) {
      inPriority = false;
    }

    // Section headers: ### Tech name — verdict
    if (line.startsWith('### ')) {
      inActions = false;
      inSection = true;
      sectionCount++;
      const rest = line.replace('### ', '');
      const parts = rest.split(' — ');
      const name = parts[0] || rest;
      const verdict = parts[1] || 'watch';
      const vClass = verdictClass(verdict.toLowerCase());

      if (sectionCount > 1) html += '</div></div>\n';

      html += `<div class="section" id="section-${sectionCount}">
  <div class="section-header">
    <span class="section-name">${escapeHtml(name)}</span>
    <span class="verdict ${vClass}">${escapeHtml(verdict)}</span>
  </div>
  <div class="section-body">`;
      continue;
    }

    if (!inSection) continue;

    // What changed label
    if (line.startsWith('**What changed:**')) {
      html += `<div class="block-label">What changed</div>
  <div class="what-changed">`;
      const content = line.replace('**What changed:**', '').trim();
      if (content) html += inlineFormat(content);
      continue;
    }

    // Action label
    if (line === '**Action:**') {
      html += `</div>\n<div class="block-label">Action</div>\n<div class="actions">`;
      inActions = true;
      continue;
    }

    // Action items
    if (inActions && line.startsWith('- 🔴')) {
      const text = line.replace('- 🔴', '').trim();
      html += `<div class="action-row"><span class="action-icon">🔴</span><span class="action-body">${inlineFormat(text)}</span></div>`;
      continue;
    }
    if (inActions && line.startsWith('- 🟡')) {
      const text = line.replace('- 🟡', '').trim();
      html += `<div class="action-row"><span class="action-icon">🟡</span><span class="action-body">${inlineFormat(text)}</span></div>`;
      continue;
    }
    if (inActions && line.startsWith('- 🔵')) {
      const text = line.replace('- 🔵', '').trim();
      html += `<div class="action-row"><span class="action-icon">🔵</span><span class="action-body">${inlineFormat(text)}</span></div>`;
      continue;
    }

    // Skipped sections
    if (inSection && !inActions && line && !line.startsWith('#') && !line.startsWith('**')) {
      html += inlineFormat(line);
    }
  }

  if (inSection) html += '</div></div></div>\n';

  return { sectionsHtml: html, priorityText: priorityText.trim() };
}

function inlineFormat(text) {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/`([^`]+)`/g, '<code>$1</code>');
}

function escapeHtml(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function buildArchiveLinks() {
  if (!existsSync('docs/archives')) return '';
  const files = readdirSync('docs/archives')
    .filter(f => f.endsWith('.html'))
    .sort()
    .reverse()
    .slice(0, 8);

  return files.map(f => {
    const date = f.replace('.html', '');
    return `<a class="archive-link" href="archives/${f}">${date}</a>`;
  }).join('\n');
}

export function buildDigestPage({ summary, items, dateStr, itemCount }) {
  const template = readFileSync('docs/index.html', 'utf-8');
  const { sectionsHtml, priorityText } = parseGeminiMarkdown(summary);

  const sourcesList = items.map(i =>
    `<div class="source-item">
      <span class="source-tag">${escapeHtml(i.label)}</span>
      <a href="${i.url}" target="_blank" rel="noopener">${escapeHtml(i.title)}</a>
    </div>`
  ).join('\n');

  const digestHtml = `
    <div class="digest-header">
      <div class="digest-week">Week of ${dateStr}</div>
      <div class="digest-title">Weekly tech digest</div>
      <div class="digest-stats">
        <div class="stat"><strong>${itemCount}</strong> items aggregated</div>
        <div class="stat">Generated by Gemini</div>
      </div>
    </div>

    ${priorityText ? `
    <div class="priority">
      <div class="priority-label">This week's priority</div>
      <div class="priority-text">${inlineFormat(priorityText)}</div>
    </div>` : ''}

    ${sectionsHtml}

    <div class="sources-section">
      <div class="sources-title">Raw sources (${itemCount})</div>
      <div class="sources-grid">
        ${sourcesList}
      </div>
    </div>
  `;

  return template
    .replace('<!-- DIGEST_PLACEHOLDER -->', digestHtml)
    .replace(
      '<div class="sidebar-archives" id="archive-links">\n        <!-- JS injects archive links -->\n      </div>',
      `<div class="sidebar-archives" id="archive-links">\n${buildArchiveLinks()}\n</div>`
    );
}
